version: '3'

services:
  database:
    container_name: database
    build: ./sport-club-management-database/
    volumes:
      - myapp:/var/lib/mysql
  
  backend:
    container_name: backend
    build: ./sport-club-management-front&back/
    depends_on:
      - database

  
    ports:
      - 80:80
    

volumes:
  myapp:
  mymodule:
    
