version: '3.8'

services:
  database:
    container_name: database
    build: .
    image: "mysql:5.7"
    ports:
    -3307:3306
    enviroments:
    MYSQL_DATABASE "sportclub"
    MYSQL_USER "root"
    MYSQL_ROOT_PASSWORD "omkar7218"
    MYSQL_PASSWORD "omkar7218"
  
  backend:
    container_name: backend
    build: .
     ports:
     -8081:8081
    depends_on:
      - database
     
  

  
  
    

    
